# tiling wm + status bar
tap "nikitabobko/tap"
tap "FelixKratz/formulae"
cask "aerospace"
brew "sketchybar"

# cli
brew "gh"

# keyboard
cask "karabiner-elements"

# apps
cask "1password"
cask "google-chrome"
cask "iterm2"
cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "rancher"
