export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="af-magic"
plugins=(
  alias-finder
  aws
  brew
  command-not-found
  docker
  docker-compose
  extract
  git
  gh
  npm
  ssh
  yarn
  z
)

# alias-finder
zstyle ':omz:plugins:alias-finder' autoload yes

source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=ja_JP.UTF-8
source ~/.dotfiles/source/alias.sh
source ~/.dotfiles/source/export.sh

# mise
eval "$(~/.local/bin/mise activate zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/naoya/Documents/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/naoya/Documents/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/naoya/Documents/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/naoya/Documents/tools/google-cloud-sdk/completion.zsh.inc'; fi
