start-at-login = true
after-startup-command = [
  'exec-and-forget sketchybar --config /Users/naoya/.config/sketchybar/sketchybarrc',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=10.0',
  'layout tiles horizontal vertical'
]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       15
outer.bottom =     10
outer.top =        40
outer.right =      15

[mode.main.binding]
cmd-h = [
  'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left',
  'move-mouse window-force-center'
]
cmd-j = [
  'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down',
  'move-mouse window-force-center'
]
cmd-k = [
  'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up',
  'move-mouse window-force-center'
]
cmd-l = [
  'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right',
  'move-mouse window-force-center'
]

cmd-ctrl-h = 'move left'
cmd-ctrl-j = 'move down'
cmd-ctrl-k = 'move up'
cmd-ctrl-l = 'move right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

cmd-ctrl-1 = ['move-node-to-workspace 1']
cmd-ctrl-2 = ['move-node-to-workspace 2']
cmd-ctrl-3 = ['move-node-to-workspace 3']
cmd-ctrl-4 = ['move-node-to-workspace 4']
cmd-ctrl-5 = ['move-node-to-workspace 5']
cmd-ctrl-6 = ['move-node-to-workspace 6']
cmd-ctrl-7 = ['move-node-to-workspace 7']
cmd-ctrl-8 = ['move-node-to-workspace 8']
cmd-ctrl-9 = ['move-node-to-workspace 9']

cmd-n = 'move-node-to-monitor --wrap-around --focus-follows-window next'
cmd-0 = 'fullscreen'
cmd-slash = 'layout tiles horizontal vertical'

[workspace-to-monitor-force-assignment]
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
