start-at-login = true
after-startup-command = [
  'layout tiles horizontal vertical'
]

[mode.main.binding]
f1 = 'workspace 1'
f2 = 'workspace 2'
f3 = 'workspace 3'
f4 = 'workspace 4'
f5 = 'workspace 5'
f6 = 'workspace 6'
f7 = 'workspace 7'
f8 = 'workspace 8'

cmd-h = ['focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left', 'move-mouse window-lazy-center']
cmd-j = ['focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down', 'move-mouse window-lazy-center']
cmd-k = ['focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up', 'move-mouse window-lazy-center']
cmd-l = ['focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right', 'move-mouse window-lazy-center']

cmd-ctrl-h = ['move left', 'move-mouse window-lazy-center']
cmd-ctrl-j = ['move down', 'move-mouse window-lazy-center']
cmd-ctrl-k = ['move up', 'move-mouse window-lazy-center']
cmd-ctrl-l = ['move right', 'move-mouse window-lazy-center']

cmd-1 = 'workspace prev'
cmd-2 = 'workspace next'

cmd-ctrl-1 = ['move-node-to-workspace prev', 'workspace prev']
cmd-ctrl-2 = ['move-node-to-workspace next', 'workspace next']

cmd-8 = 'mode resize'
cmd-9 = ['move-node-to-monitor --wrap-around --focus-follows-window next']
cmd-0 = 'fullscreen'
cmd-minus = 'layout tiles horizontal vertical'

[mode.resize.binding]
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width -50'
h = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
