start-at-login = true
after-startup-command = [
  'layout tiles horizontal vertical'
]

[mode.main.binding]
ctrl-enter = 'exec-and-forget open -n /Applications/iTerm.app'

ctrl-j = 'focus left'
ctrl-h = 'focus down'

ctrl-cmd-h = 'move left'
ctrl-cmd-j = 'move down'
ctrl-cmd-k = 'move up'
ctrl-cmd-l = 'move right'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'

ctrl-cmd-1 = 'move-node-to-workspace 1'
ctrl-cmd-2 = 'move-node-to-workspace 2'
ctrl-cmd-3 = 'move-node-to-workspace 3'
ctrl-cmd-4 = 'move-node-to-workspace 4'
ctrl-cmd-5 = 'move-node-to-workspace 5'

ctrl-8 = 'reload-config'
ctrl-9 = 'layout tiles horizontal vertical'
ctrl-0 = 'fullscreen'
ctrl-semicolon = 'mode resize' # ctrl-r is conflicts with shell history keybinding.

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
5 = 'secondary'
