start-at-login = true
after-startup-command = [
  'layout tiles horizontal vertical'
]

[mode.main.binding]
cmd-enter = 'exec-and-forget open -n /Applications/iTerm.app'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-ctrl-h = 'move left'
cmd-ctrl-j = 'move down'
cmd-ctrl-k = 'move up'
cmd-ctrl-l = 'move right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'

cmd-ctrl-1 = 'move-node-to-workspace 1'
cmd-ctrl-2 = 'move-node-to-workspace 2'
cmd-ctrl-3 = 'move-node-to-workspace 3'
cmd-ctrl-4 = 'move-node-to-workspace 4'
cmd-ctrl-5 = 'move-node-to-workspace 5'

cmd-8 = 'reload-config'
cmd-9 = 'layout tiles horizontal vertical'
cmd-0 = 'fullscreen'
cmd-semicolon = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
5 = 'secondary'
